## Load packages
library(httr2)
library(odbc)
library(DBI)
library(pool, warn.conflicts = F)
library(conflicted, warn.conflicts = F)
library(tidyverse, warn.conflicts = F)
conflicts_prefer(dplyr::select(),
                 dplyr::filter(),
                 dplyr::lag(),
                 dplyr::lead(),
                 data.table::`:=`,
                 pls::R2())
library(data.table, warn.conflicts = F)
setDTthreads(0)
library(stringr)
library(stringi, warn.conflicts = F)
library(foreach, warn.conflicts = F)
library(parallel)
library(rlang, warn.conflicts = F)
library(rvest)
library(furrr)
library(purrr, warn.conflicts = F)
library(future)
library(doFuture)
library(readtext, warn.conflicts = F)
library(qdapRegex, warn.conflicts = F)
library(nlstools, warn.conflicts = F)
library(caret, warn.conflicts = F)
library(rpart, warn.conflicts = F)
library(e1071, warn.conflicts = F)
library(splines, warn.conflicts = F)
library(forecast, warn.conflicts = F)
library(mgcv, warn.conflicts = F)
library(nlme, warn.conflicts = F)
library(minpack.lm, warn.conflicts = F)
library(nnet, warn.conflicts = F)
library(nlsMicrobio, warn.conflicts = F)
library(MASS, warn.conflicts = F)
library(ggplot2, warn.conflicts = F)
library(factoextra)
library(cluster, warn.conflicts = F)
library(tidySEM)
library(DiagrammeR)
library(lavaan)
library(pheatmap)
library(psych)
library(semptools)
library(semPlot)
library(polychoric)
library(spikeslab)
library(reshape2)
library(MCMCpack)
library(quantreg)
library(randomForest)
library(rattle)
library(rpart)
library(lmtest)
library(boot)
library(pls)
library(FinTS, warn.conflicts = F)
library(rugarch)
library(urca)